<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>main</name>
    <message>
        <source>stock monitor</source>
        <translation>股票跟踪</translation>
    </message>
    <message>
        <source>Stock Code</source>
        <translation>股票代码</translation>
    </message>
    <message>
        <source>Add</source>
        <translation>添加</translation>
    </message>
    <message>
        <source>Code</source>
        <translation>代码</translation>
    </message>
    <message>
        <source>Name</source>
        <translation>名字</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>最新价</translation>
    </message>
    <message>
        <source>Offset</source>
        <translation>涨跌额</translation>
    </message>
    <message>
        <source>Percent</source>
        <translation>涨跌幅</translation>
    </message>
    <message>
        <source>Turnover</source>
        <translation>交易额</translation>
    </message>
    <message>
        <source>Up/Down</source>
        <translation>最高/最低</translation>
    </message>
    <message>
        <source>Lose</source>
        <translation>止损价</translation>
    </message>
    <message>
        <source>Gain</source>
        <translation>止盈价</translation>
    </message>
    <message>
        <source>add comments</source>
        <translation>(股票代码只能是数字，一次添加一只；双击列表可添加提醒)</translation>
    </message>
</context>
<context>
    <name>reminder</name>
    <message>
        <source>reminder setting</source>
        <translation>提醒设置</translation>
    </message>
    <message>
        <source>Lose</source>
        <translation>止损价</translation>
    </message>
    <message>
        <source>Gain</source>
        <translation>止盈价</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <source>Apply</source>
        <translation>应用</translation>
    </message>
</context>
</TS>
